### ISSUE TITLE
Question - Notification like local-notification

### ISSUE THREAD

**Issue by natanraj** [DavidBriglio/cordova-banner-notification#5]
Will this plugin work like background notification trigger like cordova-local-notification ? I am seeing few shortfalls in that cordova-local-notification, hence checking if I could try this instead.

**Comment by DavidBriglio** [comment]
It depends on what functionality are you looking for exactly. It works in a similar way, but cannot be scheduled (only triggered). This banner is also in-app only, meaning you won't see the banner if the app is not in the foreground. The intention of this plugin is to use alongside with local notifications, for when you want a banner notification while you are inside of the application.

**Comment by natanraj** [comment]
@DavidBriglio : is there a way this plugin been made to work to show outside app (though the app may in background or not running). I am looking for widget type of notification not on status bar, but like reminder popping on homescreen / springboard.

Please excuse me - i am not a full fledged developer to contribute to Corodva. Just a small consumer using JS frameworks.

**Comment by DavidBriglio** [comment]
This plugin is only a solution to banner notifications inside of the app. If you want this type of functionality when outside the app you should look at the local notifications plugin [here](https://github.com/katzer/cordova-plugin-local-notifications). This plugin is the best option I could find.
